jobs:
  maven-cd:
    secrets:
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
name: cd
on:
  repository_dispatch:
    types: trigger-ga___cd.yaml
